const data = {
  products: [
    {
      name: 'Slim Shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 0,
      description: 'A popular TShirt',
      slug: 'slim-shirt',
    },
    {
      name: 'Fit Shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 50,
      brand: 'Adidas',
      rating: 3.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular TShirt',
      slug: 'fit-shirt',
    },
    {
      name: 'Golf Pants',
      category: 'ShPantsirts',
      image: '/images/pants1.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 4.0,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Pant',
      slug: 'golf-pants',
    },
    {
      name: 'Fit Pants',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 95,
      brand: 'ZAra',
      rating: 3.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Pants',
      slug: 'fit-pants',
    },
    {
      name: 'Long Shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 50,
      brand: 'Adidas',
      rating: 3.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular LongShirt',
      slug: 'long-shirt',
    },
    {
      name: 'Classic Pants',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 85,
      brand: 'Casely',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A classic Pants',
      slug: 'classic-pants',
    },
  ],
};
export default data;
